<?php

use Illuminate\Database\Seeder;

class ResourceGroupAccessesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('resource_group_accesses')->delete();
        
        \DB::table('resource_group_accesses')->insert(array (
            0 => 
            array (
                'id' => 1,
                'resource_group_id' => 1,
                'name' => 'Add',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:56',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            1 => 
            array (
                'id' => 2,
                'resource_group_id' => 1,
                'name' => 'Edit',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:56',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            2 => 
            array (
                'id' => 3,
                'resource_group_id' => 1,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:56',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            3 => 
            array (
                'id' => 4,
                'resource_group_id' => 1,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:56',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            4 => 
            array (
                'id' => 5,
                'resource_group_id' => 2,
                'name' => 'Add',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:56',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            5 => 
            array (
                'id' => 6,
                'resource_group_id' => 2,
                'name' => 'Edit',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            6 => 
            array (
                'id' => 7,
                'resource_group_id' => 2,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            7 => 
            array (
                'id' => 8,
                'resource_group_id' => 2,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            8 => 
            array (
                'id' => 9,
                'resource_group_id' => 3,
                'name' => 'Add',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            9 => 
            array (
                'id' => 10,
                'resource_group_id' => 3,
                'name' => 'Edit',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            10 => 
            array (
                'id' => 11,
                'resource_group_id' => 3,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            11 => 
            array (
                'id' => 12,
                'resource_group_id' => 3,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            12 => 
            array (
                'id' => 13,
                'resource_group_id' => 4,
                'name' => 'Add',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            13 => 
            array (
                'id' => 14,
                'resource_group_id' => 4,
                'name' => 'Edit',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            14 => 
            array (
                'id' => 15,
                'resource_group_id' => 4,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            15 => 
            array (
                'id' => 16,
                'resource_group_id' => 4,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            16 => 
            array (
                'id' => 17,
                'resource_group_id' => 5,
                'name' => 'Logout',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            17 => 
            array (
                'id' => 18,
                'resource_group_id' => 6,
                'name' => 'Add',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            18 => 
            array (
                'id' => 19,
                'resource_group_id' => 6,
                'name' => 'Edit',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            19 => 
            array (
                'id' => 20,
                'resource_group_id' => 6,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            20 => 
            array (
                'id' => 21,
                'resource_group_id' => 6,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            21 => 
            array (
                'id' => 22,
                'resource_group_id' => 7,
                'name' => 'Add',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            22 => 
            array (
                'id' => 23,
                'resource_group_id' => 7,
                'name' => 'Edit',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            23 => 
            array (
                'id' => 24,
                'resource_group_id' => 7,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            24 => 
            array (
                'id' => 25,
                'resource_group_id' => 7,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            25 => 
            array (
                'id' => 26,
                'resource_group_id' => 8,
                'name' => 'Add',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            26 => 
            array (
                'id' => 27,
                'resource_group_id' => 8,
                'name' => 'Edit',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            27 => 
            array (
                'id' => 28,
                'resource_group_id' => 8,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            28 => 
            array (
                'id' => 29,
                'resource_group_id' => 8,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            29 => 
            array (
                'id' => 30,
                'resource_group_id' => 9,
                'name' => 'Add',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            30 => 
            array (
                'id' => 31,
                'resource_group_id' => 9,
                'name' => 'Edit',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            31 => 
            array (
                'id' => 32,
                'resource_group_id' => 9,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            32 => 
            array (
                'id' => 33,
                'resource_group_id' => 9,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            33 => 
            array (
                'id' => 34,
                'resource_group_id' => 10,
                'name' => 'Add',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            34 => 
            array (
                'id' => 35,
                'resource_group_id' => 10,
                'name' => 'Edit',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            35 => 
            array (
                'id' => 36,
                'resource_group_id' => 10,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            36 => 
            array (
                'id' => 37,
                'resource_group_id' => 10,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            37 => 
            array (
                'id' => 38,
                'resource_group_id' => 11,
                'name' => 'Add',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 16:37:53',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            38 => 
            array (
                'id' => 39,
                'resource_group_id' => 11,
                'name' => 'Edit',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            39 => 
            array (
                'id' => 40,
                'resource_group_id' => 11,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            40 => 
            array (
                'id' => 41,
                'resource_group_id' => 11,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 12:52:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            41 => 
            array (
                'id' => 42,
                'resource_group_id' => 12,
                'name' => 'Add',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 20:32:09',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            42 => 
            array (
                'id' => 43,
                'resource_group_id' => 12,
                'name' => 'Edit',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 20:32:09',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            43 => 
            array (
                'id' => 44,
                'resource_group_id' => 12,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 20:32:09',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            44 => 
            array (
                'id' => 45,
                'resource_group_id' => 12,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 20:32:09',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            45 => 
            array (
                'id' => 46,
                'resource_group_id' => 13,
                'name' => 'Add',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 20:32:09',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            46 => 
            array (
                'id' => 47,
                'resource_group_id' => 13,
                'name' => 'Edit',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 20:32:09',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            47 => 
            array (
                'id' => 48,
                'resource_group_id' => 13,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 20:32:09',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            48 => 
            array (
                'id' => 49,
                'resource_group_id' => 13,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 20:32:09',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            49 => 
            array (
                'id' => 50,
                'resource_group_id' => 14,
                'name' => 'Add',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 20:32:09',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            50 => 
            array (
                'id' => 51,
                'resource_group_id' => 14,
                'name' => 'Edit',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 20:32:09',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            51 => 
            array (
                'id' => 52,
                'resource_group_id' => 14,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 20:32:09',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            52 => 
            array (
                'id' => 53,
                'resource_group_id' => 14,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 20:32:09',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            53 => 
            array (
                'id' => 54,
                'resource_group_id' => 15,
                'name' => 'Add',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 20:32:09',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            54 => 
            array (
                'id' => 55,
                'resource_group_id' => 15,
                'name' => 'Edit',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 20:32:09',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            55 => 
            array (
                'id' => 56,
                'resource_group_id' => 15,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 20:32:09',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            56 => 
            array (
                'id' => 57,
                'resource_group_id' => 15,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-11-26 20:32:09',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            57 => 
            array (
                'id' => 58,
                'resource_group_id' => 16,
                'name' => 'Add',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-12-03 12:36:33',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            58 => 
            array (
                'id' => 59,
                'resource_group_id' => 16,
                'name' => 'Edit',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-12-03 12:36:38',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            59 => 
            array (
                'id' => 60,
                'resource_group_id' => 16,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-12-03 12:36:45',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            60 => 
            array (
                'id' => 61,
                'resource_group_id' => 16,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-12-03 12:36:49',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            61 => 
            array (
                'id' => 62,
                'resource_group_id' => 16,
                'name' => 'Reset',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-12-04 19:10:12',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            62 => 
            array (
                'id' => 63,
                'resource_group_id' => 17,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-12-10 18:12:28',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            63 => 
            array (
                'id' => 64,
                'resource_group_id' => 4,
                'name' => 'Convert',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-12-14 18:24:16',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            64 => 
            array (
                'id' => 65,
                'resource_group_id' => 12,
                'name' => 'Convert',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-12-14 18:24:41',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            65 => 
            array (
                'id' => 66,
                'resource_group_id' => 6,
                'name' => 'Payment',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-12-29 17:50:16',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            66 => 
            array (
                'id' => 67,
                'resource_group_id' => 2,
                'name' => 'Payment',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-12-29 17:56:01',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            67 => 
            array (
                'id' => 68,
                'resource_group_id' => 8,
                'name' => 'Payment',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-12-29 17:56:08',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            68 => 
            array (
                'id' => 69,
                'resource_group_id' => 13,
                'name' => 'Payment',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-12-29 17:56:47',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            69 => 
            array (
                'id' => 70,
                'resource_group_id' => 14,
                'name' => 'Payment',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-12-29 17:56:51',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            70 => 
            array (
                'id' => 71,
                'resource_group_id' => 15,
                'name' => 'Payment',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2016-12-29 17:56:58',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            71 => 
            array (
                'id' => 72,
                'resource_group_id' => 18,
                'name' => 'Commission',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-03-28 20:13:20',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            72 => 
            array (
                'id' => 73,
                'resource_group_id' => 18,
                'name' => 'Invoice Transaction List',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-03-28 20:13:20',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            73 => 
            array (
                'id' => 74,
                'resource_group_id' => 18,
                'name' => 'Product Order List',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-03-28 20:13:20',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            74 => 
            array (
                'id' => 75,
                'resource_group_id' => 18,
                'name' => 'Cross Selling Commission',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-03-28 20:13:20',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            75 => 
            array (
                'id' => 76,
                'resource_group_id' => 6,
                'name' => 'Create Invoice',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-01-18 23:35:44',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            76 => 
            array (
                'id' => 77,
                'resource_group_id' => 6,
                'name' => 'Update Charges',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-03-11 22:31:23',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            77 => 
            array (
                'id' => 78,
                'resource_group_id' => 19,
                'name' => 'Add',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-03-16 03:09:59',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            78 => 
            array (
                'id' => 79,
                'resource_group_id' => 19,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-03-16 03:09:59',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            79 => 
            array (
                'id' => 80,
                'resource_group_id' => 19,
                'name' => 'Assign',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-03-16 03:09:59',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            80 => 
            array (
                'id' => 81,
                'resource_group_id' => 19,
                'name' => 'Close',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-03-16 03:09:59',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            81 => 
            array (
                'id' => 82,
                'resource_group_id' => 19,
                'name' => 'Merge',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-03-16 03:09:59',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            82 => 
            array (
                'id' => 83,
                'resource_group_id' => 19,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-03-16 03:09:59',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            83 => 
            array (
                'id' => 84,
                'resource_group_id' => 19,
                'name' => 'Pickup',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'I',
                'created_at' => '2017-03-16 03:14:05',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            84 => 
            array (
                'id' => 85,
                'resource_group_id' => 19,
                'name' => 'Admin Access',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-03-16 03:09:59',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            85 => 
            array (
                'id' => 86,
                'resource_group_id' => 18,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-03-28 20:13:20',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            86 => 
            array (
                'id' => 87,
                'resource_group_id' => 9,
                'name' => 'Create Template',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-04-05 00:06:09',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            87 => 
            array (
                'id' => 88,
                'resource_group_id' => 6,
                'name' => 'Sign Document',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-04-09 00:10:24',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            88 => 
            array (
                'id' => 89,
                'resource_group_id' => 18,
                'name' => 'Credit Card Sales',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-04-13 21:14:50',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            89 => 
            array (
                'id' => 90,
                'resource_group_id' => 8,
                'name' => 'Create Contact',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-04-28 02:50:35',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            90 => 
            array (
                'id' => 91,
                'resource_group_id' => 8,
                'name' => 'Edit Contact',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-04-28 02:50:35',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            91 => 
            array (
                'id' => 92,
                'resource_group_id' => 14,
                'name' => 'Create Contact',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-04-28 02:50:35',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            92 => 
            array (
                'id' => 93,
                'resource_group_id' => 14,
                'name' => 'Edit Contact',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-04-28 02:50:35',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            93 => 
            array (
                'id' => 94,
                'resource_group_id' => 15,
                'name' => 'Create Contact',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-04-28 02:50:35',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            94 => 
            array (
                'id' => 95,
                'resource_group_id' => 15,
                'name' => 'Edit Contact',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-04-28 02:50:35',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            95 => 
            array (
                'id' => 96,
                'resource_group_id' => 2,
                'name' => 'Create Contact',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-04-28 02:50:35',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            96 => 
            array (
                'id' => 97,
                'resource_group_id' => 2,
                'name' => 'Edit Contact',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-04-28 02:50:35',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            97 => 
            array (
                'id' => 98,
                'resource_group_id' => 13,
                'name' => 'Create Contact',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-04-28 02:50:35',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            98 => 
            array (
                'id' => 99,
                'resource_group_id' => 13,
                'name' => 'Edit Contact',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-04-28 02:50:35',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            99 => 
            array (
                'id' => 100,
                'resource_group_id' => 20,
                'name' => 'Create',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-06-30 18:18:20',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            100 => 
            array (
                'id' => 101,
                'resource_group_id' => 20,
                'name' => 'Edit',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-06-30 18:18:20',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            101 => 
            array (
                'id' => 102,
                'resource_group_id' => 20,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-06-30 18:18:20',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            102 => 
            array (
                'id' => 103,
                'resource_group_id' => 20,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-06-30 18:18:20',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            103 => 
            array (
                'id' => 104,
                'resource_group_id' => 21,
                'name' => 'Create',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-06-30 18:18:20',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            104 => 
            array (
                'id' => 105,
                'resource_group_id' => 21,
                'name' => 'Edit',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-06-30 18:18:20',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            105 => 
            array (
                'id' => 106,
                'resource_group_id' => 21,
                'name' => 'Delete',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-06-30 18:18:20',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            106 => 
            array (
                'id' => 107,
                'resource_group_id' => 21,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-06-30 18:18:20',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            107 => 
            array (
                'id' => 108,
                'resource_group_id' => 6,
                'name' => 'Create Returns',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-06-30 18:18:20',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            108 => 
            array (
                'id' => 111,
                'resource_group_id' => 17,
                'name' => 'Set Access',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-07-21 19:05:30',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            109 => 
            array (
                'id' => 112,
                'resource_group_id' => 17,
                'name' => 'Create',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-07-21 19:05:30',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            110 => 
            array (
                'id' => 113,
                'resource_group_id' => 1,
                'name' => 'Module',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-08 23:05:23',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            111 => 
            array (
                'id' => 114,
                'resource_group_id' => 1,
                'name' => 'Department',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-08 23:05:23',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            112 => 
            array (
                'id' => 115,
                'resource_group_id' => 6,
                'name' => 'Work Flow',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-11 00:30:04',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            113 => 
            array (
                'id' => 116,
                'resource_group_id' => 6,
                'name' => 'History-Setup',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'I',
                'created_at' => '2017-08-11 00:30:04',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            114 => 
            array (
                'id' => 117,
                'resource_group_id' => 6,
                'name' => 'Create Order',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-11 00:30:04',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            115 => 
            array (
                'id' => 118,
                'resource_group_id' => 6,
                'name' => 'Request Signature',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-11 00:30:04',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            116 => 
            array (
                'id' => 119,
                'resource_group_id' => 6,
                'name' => 'Add Product',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'I',
                'created_at' => '2017-08-11 00:30:04',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            117 => 
            array (
                'id' => 120,
                'resource_group_id' => 6,
                'name' => 'Returns',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-11 00:30:04',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            118 => 
            array (
                'id' => 121,
                'resource_group_id' => 6,
                'name' => 'Pay Invoice',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-11 00:30:04',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            119 => 
            array (
                'id' => 122,
                'resource_group_id' => 6,
                'name' => 'Void Invoice',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-11 00:30:04',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            120 => 
            array (
                'id' => 123,
                'resource_group_id' => 6,
                'name' => 'Edit Invoice',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-11 00:30:04',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            121 => 
            array (
                'id' => 124,
                'resource_group_id' => 6,
                'name' => 'Merge Invoice',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-11 00:30:04',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            122 => 
            array (
                'id' => 125,
                'resource_group_id' => 6,
                'name' => 'View Invoice',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-11 00:30:04',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            123 => 
            array (
                'id' => 126,
                'resource_group_id' => 9,
                'name' => 'Welcome Email',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-24 18:46:52',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            124 => 
            array (
                'id' => 127,
                'resource_group_id' => 6,
                'name' => 'Welcome Email',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-24 18:46:52',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            125 => 
            array (
                'id' => 128,
                'resource_group_id' => 8,
                'name' => 'Edit Commission',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-30 18:22:43',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            126 => 
            array (
                'id' => 129,
                'resource_group_id' => 14,
                'name' => 'Edit Commission',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-30 18:22:43',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            127 => 
            array (
                'id' => 130,
                'resource_group_id' => 15,
                'name' => 'Edit Commission',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-30 18:22:43',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            128 => 
            array (
                'id' => 131,
                'resource_group_id' => 13,
                'name' => 'Edit Commission',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-30 18:22:43',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            129 => 
            array (
                'id' => 132,
                'resource_group_id' => 2,
                'name' => 'Edit Commission',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-08-30 18:22:43',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            130 => 
            array (
                'id' => 133,
                'resource_group_id' => 9,
                'name' => 'Work Flow',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-09-06 18:26:08',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            131 => 
            array (
                'id' => 134,
                'resource_group_id' => 9,
                'name' => 'Commission Template',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-09-06 18:26:08',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            132 => 
            array (
                'id' => 135,
                'resource_group_id' => 22,
                'name' => 'View',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-09-29 19:08:42',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            133 => 
            array (
                'id' => 136,
                'resource_group_id' => 4,
                'name' => 'Calendar',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-10-02 19:08:25',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            134 => 
            array (
                'id' => 137,
                'resource_group_id' => 16,
                'name' => 'Full Access',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-11-20 10:14:57',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            135 => 
            array (
                'id' => 138,
                'resource_group_id' => 6,
                'name' => 'Status',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2018-03-26 09:16:37',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            136 => 
            array (
                'id' => 139,
                'resource_group_id' => 1,
                'name' => 'Department Full Access',
                'create_by' => NULL,
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            137 => 
            array (
                'id' => 140,
                'resource_group_id' => 1,
                'name' => 'Company Settings',
                'create_by' => NULL,
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            138 => 
            array (
                'id' => 141,
                'resource_group_id' => 19,
                'name' => 'Reply Template',
                'create_by' => NULL,
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            139 => 
            array (
                'id' => 142,
                'resource_group_id' => 1,
                'name' => 'Super Admin Access',
                'create_by' => NULL,
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            140 => 
            array (
                'id' => 143,
                'resource_group_id' => 2,
                'name' => 'View Agent Applicants',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => '2017-09-29 19:08:42',
                'updated_at' => '2018-06-07 01:36:20',
            ),
            141 => 
            array (
                'id' => 144,
                'resource_group_id' => 6,
                'name' => 'Order Billing Id',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            142 => 
            array (
                'id' => 145,
                'resource_group_id' => 6,
                'name' => 'Paid Product Invoices',
                'create_by' => 'Seeder',
                'update_by' => NULL,
                'status' => 'A',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            143 =>
                array (
                    'id' => 146,
                    'resource_group_id' => 1,
                    'name' => 'Owner Access',
                    'create_by' => 'Seeder',
                    'update_by' => NULL,
                    'status' => 'A',
                    'created_at' => NULL,
                    'updated_at' => NULL,
                ),
            144 => 
                array (
                    'id' => 147,
                    'resource_group_id' => 6,
                    'name' => 'Edit Workflow',
                    'create_by' => 'Seeder',
                    'update_by' => NULL,
                    'status' => 'A',
                    'created_at' => '2017-08-11 00:30:04',
                    'updated_at' => '2018-06-07 01:36:20',
                ),
            145 => 
                array (
                    'id' => 148,
                    'resource_group_id' => 6,
                    'name' => 'Delete Workflow Tasks',
                    'create_by' => 'Seeder',
                    'update_by' => NULL,
                    'status' => 'A',
                    'created_at' => '2017-08-11 00:30:04',
                    'updated_at' => '2018-06-07 01:36:20',
                ),
            146 => 
                array (
                    'id' => 149,
                    'resource_group_id' => 16,
                    'name' => 'Set as Offline',
                    'create_by' => 'Seeder',
                    'update_by' => NULL,
                    'status' => 'A',
                    'created_at' => '2017-11-13 00:30:04',
                    'updated_at' => '2018-11-13 01:36:20',
                ),
            146 => 
                array (
                    'id' => 150,
                    'resource_group_id' => 6,
                    'name' => 'Order List',
                    'create_by' => 'Seeder',
                    'update_by' => NULL,
                    'status' => 'A',
                    'created_at' => '2017-11-13 00:30:04',
                    'updated_at' => '2018-11-13 01:36:20',
                ),
            147 => 
                array (
                    'id' => 151,
                    'resource_group_id' => 6,
                    'name' => 'Process Order',
                    'create_by' => 'Seeder',
                    'update_by' => NULL,
                    'status' => 'A',
                    'created_at' => '2017-11-21 00:30:04',
                    'updated_at' => '2018-11-21 01:36:20',
                ),

            148 => 
                array (
                    'id' => 152,
                    'resource_group_id' => 6,
                    'name' => 'Assign Workflow',
                    'create_by' => 'Seeder',
                    'update_by' => NULL,
                    'status' => 'A',
                    'created_at' => '2017-08-11 00:30:04',
                    'updated_at' => '2018-06-07 01:36:20',
                ),

        ));
        
        
    }
}