<?php

namespace App\Notifications\Tickets;

use App\Channels\SystemChannel;
use App\Models\TicketHeader;
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;

class TicketCreatedNotification extends Notification
{
    use Queueable;

    protected $ticketHeader;

    public function __construct(TicketHeader $ticketHeader)
    {
        $this->ticketHeader = $ticketHeader;
    }

    public function via($notifiable)
    {
        return [SystemChannel::class];
    }

    public function toSystem($notifiable)
    {
        $data = [
            'partner_id' => -1,
            'source_id' => -1,
            'subject' => "Ticket #{$this->ticketHeader->id} created",
            'redirect_url' => "/tickets/{$this->ticketHeader->id}/edit",
            'recipient' => $notifiable->username,
        ];

        if (isset($this->ticketHeader->createdBy)) {
            $creator = $this->ticketHeader->createdBy->full_name;
            $data['message'] = "{$creator} created a ticket.";
        } else {
            $orderId = $this->ticketHeader->subTaskDetail->task->order_id;
            $data['create_by'] = 'SYSTEM'; 
            $data['update_by'] = 'SYSTEM';
            $data['message'] = 
                "Autogenerated ticket from " .
                "product order {$orderId} workflow.";
        }

        return $data;
    }
}
